### ISSUE TITLE
Check URI.equals() for URL equality

### ISSUE THREAD

**Issue by zhanghai** [bitfireAT/dav4jvm#42]
A server may return a Location header with a differently percentage encoded value, e.g. whether to encode `[` and `]`. `rclone serve webdav` is one server that has this behavior. Since we are already creating URI instances from HttpUrl, we can just compare them to check for this kind of equality.

This is from #41 but without the actual one-line code because I might not be abel to sign the CLA.

**Comment by zhanghai** [comment]
I found that creating the `URI` and calling `URI.equals()` solves the problem for `[]` v.s. `%5B%5C`, but `!` v.s. `%21` is still not handled...

**Comment by rfc2822** [comment]
Can you please provide a list of cases + what you would expect so that we can test against these cases (see `UrlUtilsTest.testEquals`)?

Then the code can be adapted.

**Comment by zhanghai** [comment]
- `https://www.example.com/folder/[X]Y!.txt` (minimally encoded for URL)
- `https://www.example.com/folder/%5BX%5DY!.txt` (`[]` encoded for URI)
- `https://www.example.com/folder/%5BX%5DY％21.txt` (`!` unnecessarily encoded)

Since these are just the same path with different choices for what to percent encode, the should all be considered equal.

**Comment by rfc2822** [comment]
I agree that `UrlUtils.equals()` should return true in this case… unfortunately it's not that easy because they're not really equal and it's only a guess for interpreting WebDAV responses.

For instance, things become complicated with encoded slashes… or encoded non-ASCII characters (no one says that they must be with UTF-8 or whatever).

My approach was to "decode" (= convert %xx to character) as much as possible of the two compared URLs and then compare them.

**Comment by rfc2822** [comment]
So if you can provide a PR that improves / implements this approach (+ tests) it would be welcome.

**Comment by zhanghai** [comment]
As mentioned earlier, we can have an additional check for equality in `UrlUtils.equals()` with `uri1.scheme.equals(uri2.scheme, true) && uri1.schemeSpecificPart == uri2.schemeSpecificPart`, where `Uri.schemeSpecificPart` returns decoded SSP and will work.

**Comment by rfc2822** [comment]
> `uri1.scheme.equals(uri2.scheme, true) && uri1.schemeSpecificPart == uri2.schemeSpecificPart`, where `Uri.schemeSpecificPart` returns decoded SSP and will work.

It works for the `[]`, but for some reason, `getSchemeSpecificPart` doesn't decode `%21` to `!` here…

**Comment by zhanghai** [comment]
It works for me:

```
jshell> new java.net.URI("https://example.com/%21.txt").getSchemeSpecificPart()
$1 ==> "//example.com/!.txt"
```

**Comment by rfc2822** [comment]
Ok, the problem in `UrlUtilsTest` comes from `"%".toHttpUrl()`, which encodes the `%` of `%21`, so that `schemeSpecificPart` decodes it again, but it's still `%21` instead of `!`.

So just adding this equality check won't make the tests in the current form work.

Where do you get your HttpUrl from? Is it ensured that it's not made over `<string, potentially containing %>.toHttpUrl()` which then encodes the `%`?

**Comment by zhanghai** [comment]
It comes from the `Location` response header sent by `rclone serve webdav`, which is read by dav4jvm at https://github.com/bitfireAT/dav4jvm/blob/f428759cdd77abb5e9fba44408038143c2d1a570/src/main/kotlin/at/bitfire/dav4jvm/Response.kt#L161C61-L161C76

I don't think `String.toHttpUrl()` should encode the "%" though, because the source string should already be a valid URL and have percent encoding in it.

**Comment by rfc2822** [comment]
The test with the "%" didn't work because the "%" was actually another Unicode sign: "％"

See #43 for amended tests, where now all `[]!` work. If there's still a problem, please open a new issue with a test describing the problem. If you don't wish the test to be taken to be into the source code, you can annotate it somehow. However without a test that illustrates the problem I can't provide a fix.
